#!/usr/bin/env python3
"""Global theme switcher.

One palette per theme lives in themes/<name>.json. Everything else on this
box is generated from it, so a theme is defined in exactly one place:

    theme list          # show the themes and which one is live
    theme icons         # rebuild the icon index (after installing apps)
    theme recolor <base> <#hex> <name>   # a Material-Black set in any colour
    theme set <name>    # switch to it
    theme apply         # re-render the current theme (run at Hyprland start)
    theme next          # cycle

Generated files carry a "GENERATED by ~/.config/theme" header. Editing them
directly is pointless — the next switch overwrites them. Edit the JSON, then
`theme apply`.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

HOME = Path.home()
CONF = HOME / ".config"
ROOT = CONF / "theme"
THEMES = ROOT / "themes"
STATE = ROOT / "current"
WALLPAPERS = CONF / "hypr" / "wallpapers"
CACHE = HOME / ".cache" / "theme"

BANNER = "GENERATED by ~/.config/theme — edit themes/{name}.json and run `theme apply`."


# -- helpers -----------------------------------------------------------------


def load(name: str) -> dict:
    path = THEMES / f"{name}.json"
    if not path.exists():
        die(f"no such theme: {name}\navailable: {', '.join(names())}")
    theme = json.loads(path.read_text())
    theme["_banner"] = BANNER.format(name=name)
    return theme


def names() -> list[str]:
    return sorted(p.stem for p in THEMES.glob("*.json"))


def current() -> str:
    if STATE.exists():
        name = STATE.read_text().strip()
        if name in names():
            return name
    return names()[0]


def die(msg: str) -> None:
    print(f"theme: {msg}", file=sys.stderr)
    sys.exit(1)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def run(*cmd: str, check: bool = False) -> subprocess.CompletedProcess | None:
    """Best-effort side effect. A missing binary or a dead daemon is not fatal:
    the file on disk is already correct, so the next start picks it up."""
    if not shutil.which(cmd[0]):
        return None
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=15, check=check)
    except (subprocess.SubprocessError, OSError) as exc:
        print(f"theme: {cmd[0]}: {exc}", file=sys.stderr)
        return None


def sub_line(path: Path, pattern: str, replacement: str) -> None:
    """Rewrite one setting in a config we don't own outright."""
    if not path.exists():
        return
    text = path.read_text()
    new, n = re.subn(pattern, replacement, text, flags=re.MULTILINE)
    if n:
        path.write_text(new)


def set_ini_key(path: Path, section: str, key: str, value: str) -> None:
    """Set key=value in an ini file, creating the file, the section or the key
    as needed. sub_line() alone silently does nothing when the key is absent,
    which is how a config can end up stranded on the previous theme."""
    line = f"{key}={value}"
    text = path.read_text() if path.exists() else ""

    if re.search(rf"^{re.escape(key)}=", text, re.MULTILINE):
        text = re.sub(rf"^{re.escape(key)}=.*$", line, text, flags=re.MULTILINE)
    elif re.search(rf"^\[{re.escape(section)}\]", text, re.MULTILINE):
        text = re.sub(rf"^(\[{re.escape(section)}\])", rf"\1\n{line}", text, count=1, flags=re.MULTILINE)
    else:
        text = f"{text.rstrip()}\n\n[{section}]\n{line}\n".lstrip()

    write(path, text)


def strip_hash(c: str) -> str:
    return c.lstrip("#")


def rgba(c: str, a: float) -> str:
    """Hyprland's rgba(RRGGBBAA)."""
    return f"rgba({strip_hash(c)}{round(a * 255):02x})"


# -- renderers ---------------------------------------------------------------
#
# Each takes the theme dict and writes files; live-reload side effects go at
# the end of apply() so a dry file render stays cheap.


def render_quickshell(t: dict) -> None:
    c = t["colors"]
    lines = "\n".join(f'\treadonly property color {k}: "{v}"' for k, v in c.items())
    write(
        CONF / "quickshell" / "generated" / "Colors.qml",
        f"""pragma Singleton

import Quickshell
import QtQuick

// {t["_banner"]}
//
// Theme.qml aliases these, so every widget keeps reading Theme.<colour> and
// only this file changes when the theme does. Quickshell watches its config
// directory, so writing this hot-reloads the bar.
Singleton {{
\treadonly property string themeName: "{t["name"]}"
\treadonly property string themeLabel: "{t["label"]}"

{lines}
}}
""",
    )


ICON_ROOTS = (
    HOME / ".local/share/icons",
    HOME / ".icons",
    Path("/usr/share/icons"),
)
# Categories worth indexing: app launchers, notification icons, tray icons.
ICON_CATEGORIES = ("apps", "status", "devices", "places", "actions", "categories")


def icon_theme_chain(name: str) -> list[Path]:
    """A theme plus whatever it inherits, in lookup order, ending at hicolor."""
    chain: list[Path] = []
    seen: set[str] = set()
    queue = [name, "hicolor"]

    while queue:
        theme = queue.pop(0)
        if theme in seen:
            continue
        seen.add(theme)

        for root in ICON_ROOTS:
            directory = root / theme
            if not directory.is_dir():
                continue
            chain.append(directory)
            index = directory / "index.theme"
            if index.exists():
                for line in index.read_text(errors="ignore").splitlines():
                    if line.startswith("Inherits="):
                        queue.extend(p.strip() for p in line.split("=", 1)[1].split(","))
    return chain


def render_icons(t: dict) -> None:
    """Index icon-name -> file, because Qt inside Quickshell has no icon theme.

    Setting one needs a platform theme plugin (qt6ct or the gtk one), neither of
    which is installed, so `Quickshell.iconPath()` and `image://icon/...` only
    ever resolve absolute paths. The shell reads this index instead; see
    services/Icons.qml.
    """
    out = CONF / "quickshell" / "generated" / "icons.json"
    marker = out.with_suffix(".theme")
    icon_theme = t["gtk"]["icons"]

    if out.exists() and marker.exists() and marker.read_text().strip() == icon_theme:
        return

    # Each theme has its own icon set, so a naive rebuild costs ~1.6s of disk
    # walking on every single switch. Cached per icon theme, that becomes a
    # 2.5MB copy. `theme icons` clears the cache when new apps are installed.
    cache = CACHE / f"icons-{icon_theme}.json"
    if cache.exists():
        write(out, cache.read_text())
        write(marker, icon_theme + "\n")
        return

    index: dict[str, str] = {}

    def add(path: Path) -> None:
        index.setdefault(path.stem, str(path))

    def size_rank(name: str) -> tuple[int, int]:
        """Bigger (and scalable) wins: a 512px source beats a 16px one for a
        34px notification badge."""
        if name.startswith("scalable"):
            return (1, 0)
        head = name.split("x")[0].split("@")[0]
        return (0, int(head) if head.isdigit() else 0)

    for theme_dir in icon_theme_chain(t["gtk"]["icons"]):
        # Two layouts in the wild: Papirus nests size/category, the Suru themes
        # nest category/size. Walk both by checking which half of each pair
        # names a category.
        for outer in sorted(
            (d for d in theme_dir.iterdir() if d.is_dir()), key=lambda d: size_rank(d.name), reverse=True
        ):
            if outer.name in ICON_CATEGORIES:
                inner_dirs = sorted(
                    (d for d in outer.iterdir() if d.is_dir()), key=lambda d: size_rank(d.name), reverse=True
                )
            else:
                inner_dirs = [outer / category for category in ICON_CATEGORIES]

            for directory in inner_dirs:
                if not directory.is_dir():
                    continue
                for icon in directory.iterdir():
                    if icon.suffix in (".svg", ".png", ".xpm"):
                        add(icon)

    # Legacy drop-box a lot of third-party packages still use.
    pixmaps = Path("/usr/share/pixmaps")
    if pixmaps.is_dir():
        for icon in pixmaps.iterdir():
            if icon.suffix in (".svg", ".png", ".xpm"):
                add(icon)

    payload = json.dumps(index, separators=(",", ":"), sort_keys=True)
    write(out, payload)
    write(cache, payload)
    write(marker, icon_theme + "\n")


def render_kitty(t: dict) -> None:
    c, term = t["colors"], t["term"]
    write(
        CONF / "kitty" / "theme.conf",
        f"""# {t["_banner"]}

foreground           {term["fg"]}
background           {term["bg"]}
selection_foreground none
selection_background {term["selectionBg"]}

cursor               {term["cursor"]}
cursor_text_color    {term["bg"]}

# normal
color0  {term["black"]}
color1  {c["red"]}
color2  {c["green"]}
color3  {c["orange"]}
color4  {c["blue"]}
color5  {c["purple"]}
color6  {c["cyan"]}
color7  {term["white"]}

# bright
color8  {term["brightBlack"]}
color9  {c["red"]}
color10 {c["green"]}
color11 {c["yellow"]}
color12 {c["blue"]}
color13 {c["purple"]}
color14 {c["cyan"]}
color15 {term["brightWhite"]}
""",
    )


def render_alacritty(t: dict) -> None:
    c, term = t["colors"], t["term"]

    def x(col: str) -> str:
        return f"'0x{strip_hash(col)}'"

    write(
        CONF / "alacritty" / "colors.toml",
        f"""# {t["_banner"]}

[colors.primary]
background = {x(term["bg"])}
foreground = {x(term["fg"])}
bright_foreground = {x(term["brightWhite"])}

[colors.cursor]
text = {x(term["bg"])}
cursor = {x(term["cursor"])}

[colors.selection]
background = {x(term["selectionBg"])}
text = 'CellForeground'

[colors.normal]
black =   {x(term["black"])}
red =     {x(c["red"])}
green =   {x(c["green"])}
yellow =  {x(c["orange"])}
blue =    {x(c["blue"])}
magenta = {x(c["purple"])}
cyan =    {x(c["cyan"])}
white =   {x(term["white"])}

[colors.bright]
black =   {x(term["brightBlack"])}
red =     {x(c["red"])}
green =   {x(c["green"])}
yellow =  {x(c["yellow"])}
blue =    {x(c["blue"])}
magenta = {x(c["purple"])}
cyan =    {x(c["cyan"])}
white =   {x(term["brightWhite"])}
""",
    )


def render_nvim(t: dict) -> None:
    c = t["colors"]
    entries = "\n".join(f'\t\t{k} = "{v}",' for k, v in c.items())
    write(
        CONF / "nvim" / "lua" / "theme.lua",
        f"""-- {t["_banner"]}
--
-- lua/plugins/colorscheme.lua reads this to pick the colorscheme and to patch
-- the handful of highlights (comments, float borders) the shell keeps in sync.
return {{
\tname = "{t["name"]}",
\tcolorscheme = "{t["editors"]["nvim"]}",
\tcolors = {{
{entries}
\t}},
}}
""",
    )


def render_doom(t: dict) -> None:
    c = t["colors"]
    write(
        CONF / "doom" / "theme.el",
        f""";;; theme.el -*- lexical-binding: t; -*-
;; {t["_banner"]}
;;
;; config.el loads this. The face overrides mirror the ones that used to be
;; hardcoded there (true-black background, cyan child-frame borders) but track
;; the active palette instead.

(setq doom-theme '{t["editors"]["doom"]})

(custom-set-faces!
  '(default              :background "{t["term"]["bg"]}")
  '(solaire-default-face :background "{t["term"]["bg"]}")
  '(hl-line              :background "{c["surface"]}")
  '(child-frame-border   :background "{c["accent"]}")
  '(vertical-border      :foreground "{c["accent"]}")
  ;; The reason this file exists: comment contrast. Themes vary in how far
  ;; they sink comments into the background; this pins them at a measured
  ;; ratio against the editor background instead.
  '(font-lock-comment-face :foreground "{c["comment"]}")
  '(font-lock-doc-face     :foreground "{c["comment"]}")
  '(mode-line              :family "UbuntuMono Nerd Font")
  '(mode-line-inactive     :family "UbuntuMono Nerd Font"))
""",
    )


def render_hypr(t: dict) -> None:
    c = t["colors"]
    wallpaper = WALLPAPERS / t["wallpaper"]

    write(
        CONF / "hypr" / "hyprpaper.conf",
        f"""# {t["_banner"]}

wallpaper {{
  monitor =
  path = {wallpaper}
}}

splash = false
""",
    )

    # hyprlock.conf sources this.
    write(
        CONF / "hypr" / "colors.conf",
        f"""# {t["_banner"]}

$wallpaper = {wallpaper}

$base = {rgba(c["base"], 1)}
$surface = {rgba(c["surface"], 1)}
$outline = {rgba(c["outline"], 1)}
$fg = {rgba(c["fg"], 1)}
$fgDim = {rgba(c["fgDim"], 1)}
$accent = {rgba(c["accent"], 1)}
$blue = {rgba(c["blue"], 1)}
$green = {rgba(c["green"], 1)}
$red = {rgba(c["red"], 1)}
$orange = {rgba(c["orange"], 1)}
""",
    )


def render_btop(t: dict) -> None:
    c, term = t["colors"], t["term"]
    write(
        CONF / "btop" / "themes" / f"{t['name']}.theme",
        f"""# {t["_banner"]}

theme[main_bg]="{term["bg"]}"
theme[main_fg]="{c["fg"]}"
theme[title]="{c["fg"]}"
theme[hi_fg]="{c["accent"]}"
theme[selected_bg]="{c["surfaceBright"]}"
theme[selected_fg]="{c["accent"]}"
theme[inactive_fg]="{c["fgFaint"]}"
theme[graph_text]="{c["fgDim"]}"
theme[meter_bg]="{c["surfaceBright"]}"
theme[proc_misc]="{c["green"]}"
theme[cpu_box]="{c["outline"]}"
theme[mem_box]="{c["outline"]}"
theme[net_box]="{c["outline"]}"
theme[proc_box]="{c["outline"]}"
theme[div_line]="{c["outline"]}"
theme[temp_start]="{c["green"]}"
theme[temp_mid]="{c["yellow"]}"
theme[temp_end]="{c["red"]}"
theme[cpu_start]="{c["cyan"]}"
theme[cpu_mid]="{c["blue"]}"
theme[cpu_end]="{c["purple"]}"
theme[free_start]="{c["green"]}"
theme[free_mid]="{c["cyan"]}"
theme[free_end]="{c["blue"]}"
theme[cached_start]="{c["blue"]}"
theme[cached_mid]="{c["purple"]}"
theme[cached_end]="{c["purple"]}"
theme[available_start]="{c["yellow"]}"
theme[available_mid]="{c["orange"]}"
theme[available_end]="{c["orange"]}"
theme[used_start]="{c["orange"]}"
theme[used_mid]="{c["red"]}"
theme[used_end]="{c["red"]}"
theme[download_start]="{c["cyan"]}"
theme[download_mid]="{c["blue"]}"
theme[download_end]="{c["purple"]}"
theme[upload_start]="{c["green"]}"
theme[upload_mid]="{c["yellow"]}"
theme[upload_end]="{c["orange"]}"
""",
    )
    sub_line(
        CONF / "btop" / "btop.conf",
        r'^color_theme = ".*"$',
        f'color_theme = "{HOME}/.config/btop/themes/{t["name"]}.theme"',
    )


def render_gtk(t: dict) -> None:
    g = t["gtk"]

    for version in ("gtk-3.0", "gtk-4.0"):
        path = CONF / version / "settings.ini"
        set_ini_key(path, "Settings", "gtk-theme-name", g["theme"])
        set_ini_key(path, "Settings", "gtk-icon-theme-name", g["icons"])
        set_ini_key(path, "Settings", "gtk-application-prefer-dark-theme", "1")

    # GTK2 is still around (a few Xfce and Wine-adjacent dialogs) and reads a
    # completely separate file. nwg-look owns the header and includes
    # .gtkrc-2.0.mine, so keep both conventions intact and only retarget the
    # theme lines.
    gtkrc = HOME / ".gtkrc-2.0"
    if gtkrc.exists():
        sub_line(gtkrc, r'^gtk-theme-name=.*$', f'gtk-theme-name="{g["theme"]}"')
        sub_line(gtkrc, r'^gtk-icon-theme-name=.*$', f'gtk-icon-theme-name="{g["icons"]}"')
    else:
        write(
            gtkrc,
            f'# {t["_banner"]}\n'
            f'gtk-theme-name="{g["theme"]}"\n'
            f'gtk-icon-theme-name="{g["icons"]}"\n'
            'gtk-font-name="Ubuntu Nerd Font 11"\n',
        )

    # libadwaita/GTK4 apps ignore the theme name and read this file directly.
    #
    # The Material-Black themes are GTK2/3 only, so gtk4 names a separate theme
    # to borrow the GTK4 sheet from — a Colloid variant in the same palette. The
    # handful of GTK4 apps therefore stay in-palette even though they can't have
    # the Material-Black look.
    theme_dir = theme_search(g.get("gtk4") or g["theme"])
    for css in ("gtk.css", "gtk-dark.css"):
        dst = CONF / "gtk-4.0" / css
        src = theme_dir / "gtk-4.0" / css if theme_dir else None
        if dst.is_symlink() or dst.exists():
            dst.unlink()
        if src and src.exists():
            dst.symlink_to(src)


def theme_search(name: str) -> Path | None:
    for root in (HOME / ".themes", HOME / ".local/share/themes", Path("/usr/share/themes")):
        if (root / name).is_dir():
            return root / name
    return None


KVANTUM_BASE = Path("/usr/share/Kvantum/Nordic-Darker-Solid")


def render_qt(t: dict) -> None:
    """Qt apps go through Kvantum. No upstream Kvantum theme matches these
    palettes, so each one reuses a stock theme's SVG (the widget shapes) with
    its [GeneralColors] block rewritten — which is the part that reads as the
    theme."""
    c, g = t["colors"], t["gtk"]
    name = g["kvantum"]
    dest = CONF / "Kvantum" / name
    base_conf = KVANTUM_BASE / f"{KVANTUM_BASE.name}.kvconfig"

    if base_conf.exists():
        dest.mkdir(parents=True, exist_ok=True)
        svg = dest / f"{name}.svg"
        if not svg.exists():
            shutil.copy(KVANTUM_BASE / f"{KVANTUM_BASE.name}.svg", svg)

        colors = f"""[GeneralColors]
window.color={c["base"]}
base.color={c["dim"]}
alt.base.color={c["surface"]}
button.color={c["surface"]}
light.color={c["surfaceBright"]}
mid.light.color={c["surface"]}
dark.color={c["dim"]}
mid.color={c["outline"]}
highlight.color={c["accent"]}
inactive.highlight.color={c["surfaceBright"]}
text.color={c["fg"]}
window.text.color={c["fg"]}
button.text.color={c["fg"]}
disabled.text.color={c["fgFaint"]}
tooltip.text.color={c["fg"]}
highlight.text.color={c["dim"]}
link.color={c["accent"]}
link.visited.color={c["purple"]}
progress.indicator.text.color={c["fg"]}
"""
        text = base_conf.read_text()
        text = re.sub(r"\[GeneralColors\]\n(?:[^\[]*)", colors, text, count=1)
        write(dest / f"{name}.kvconfig", f"# {t['_banner']}\n{text}")

    set_ini_key(CONF / "Kvantum" / "kvantum.kvconfig", "General", "theme", name)

    # qt5ct/qt6ct: create the config if it isn't there. Beyond the icon theme,
    # this is what gives Qt an icon theme *at all* — Quickshell included, since
    # Hyprland exports QT_QPA_PLATFORMTHEME=qt6ct to everything it starts.
    for qt in ("qt5ct", "qt6ct"):
        conf = CONF / qt / f"{qt}.conf"
        set_ini_key(conf, "Appearance", "icon_theme", g["icons"])
        set_ini_key(conf, "Appearance", "style", "kvantum")
        set_ini_key(conf, "Appearance", "standard_dialogs", "default")


# Order matters: render_quickshell writes the file Quickshell watches, and the
# hot reload that follows tears down the QML engine — which kills the `theme
# set` process the picker spawned. Doing it last means everything else has
# already landed. ThemeState.qml also detaches the process; belt and braces.
RENDERERS = (
    render_icons,
    render_kitty,
    render_alacritty,
    render_nvim,
    render_doom,
    render_hypr,
    render_btop,
    render_gtk,
    render_qt,
    render_quickshell,
)


def set_wallpaper(path: Path) -> bool:
    """Point every output at `path`, and make sure it actually took.

    This hyprpaper build (0.8.4) only accepts `wallpaper` and `listactive` —
    `preload`, `unload` and `reload` all answer "invalid hyprpaper request". So
    an image that isn't already in memory can't be preloaded: the first
    `wallpaper` request kicks off an async load, returns success, and leaves the
    old wallpaper up. That's what made a theme switch appear to need doing
    twice. Re-issue until listactive agrees, which costs one extra call once the
    image is warm.
    """
    target = str(path)

    for attempt in range(24):
        # Re-issue only at the start and once more if it's clearly stuck: each
        # request makes hyprpaper decode the image again, which is what made a
        # switch spin the fans.
        if attempt in (0, 12):
            run("hyprctl", "hyprpaper", "wallpaper", f",{target}")

        active = run("hyprctl", "hyprpaper", "listactive")
        # Lines look like "DP-1: /path/to.jpg"; hyprctl's own diagnostics
        # ("error: can't send: ...") also contain a colon, so match the shape.
        paths = re.findall(r"^\S+: (/.*)$", active.stdout if active else "", re.MULTILINE)
        if paths and all(p.strip() == target for p in paths):
            return True

        # No monitors listed at all means hyprpaper isn't up — it starts
        # alongside `theme apply` at login. It reads the generated
        # hyprpaper.conf when it does come up, so there is nothing to retry.
        if not paths:
            return False

        # Decoding a 4K JPEG takes a moment; poll rather than nag.
        time.sleep(0.1)

    print(f"theme: hyprpaper did not switch to {path.name}", file=sys.stderr)
    return False



# -- live reload -------------------------------------------------------------


def reload_all(t: dict) -> None:
    c, g = t["colors"], t["gtk"]

    # Hyprland window borders. hyprland.lua does not read the palette, so these
    # are pushed live and re-pushed from autostart via `theme apply`.
    #
    # `hyprctl keyword` is refused outright by a Lua config ("keyword can't work
    # with non-legacy parsers"); `eval` runs a string against the same hl API the
    # config uses.
    run(
        "hyprctl",
        "eval",
        "hl.config({ general = { col = {"
        f' active_border = "{rgba(c["accent"], 0.93)}",'
        f' inactive_border = "{rgba(c["base"], 0.67)}"'
        " } } })",
    )
    set_wallpaper(WALLPAPERS / t["wallpaper"])

    # Notifications are drawn by the shell now, so there is no daemon to
    # reload: the cards read Theme.* and follow the hot-reloaded palette.
    #
    # kitty reloads its config on SIGUSR1; alacritty and quickshell watch their
    # own files, so they need nothing.
    run("pkill", "-USR1", "-x", "kitty")

    # GTK4/libadwaita and anything using the settings portal read gsettings,
    # not settings.ini.
    # Cursor theme is deliberately absent: it isn't part of any of these
    # palettes, and switching themes shouldn't change the pointer.
    for key, value in (
        ("gtk-theme", g["theme"]),
        ("icon-theme", g["icons"]),
        ("color-scheme", "prefer-dark"),
    ):
        run("gsettings", "set", "org.gnome.desktop.interface", key, value)



# -- commands ----------------------------------------------------------------


def apply(name: str, quiet: bool = False) -> None:
    t = load(name)
    for render in RENDERERS:
        render(t)
    STATE.write_text(name + "\n")
    reload_all(t)
    if not quiet:
        print(f"theme: {t['label']}")


def cmd_list() -> None:
    live = current()
    for name in names():
        t = load(name)
        mark = "*" if name == live else " "
        print(f" {mark} {name:<10} {t['label']:<12} {t['blurb']}")


def cmd_data() -> None:
    """Everything the Quickshell picker needs, in one read."""
    print(
        json.dumps(
            {
                "current": current(),
                "themes": [
                    {
                        "name": t["name"],
                        "label": t["label"],
                        "blurb": t["blurb"],
                        "colors": t["colors"],
                        "wallpaper": str(WALLPAPERS / t["wallpaper"]),
                    }
                    for t in (load(n) for n in names())
                ],
            }
        )
    )


def main(argv: list[str]) -> None:
    cmd = argv[0] if argv else "list"

    if cmd in ("list", "-l", "--list"):
        cmd_list()
    elif cmd == "data":
        cmd_data()
    elif cmd == "recolor":
        # Build a Material-Black + Suru-GLOW pair in an arbitrary colour.
        import recolor
        recolor.main(argv[1:])
    elif cmd == "icons":
        # Force the icon index to be rebuilt — after installing new apps or
        # changing the icon theme by hand.
        marker = CONF / "quickshell" / "generated" / "icons.theme"
        if marker.exists():
            marker.unlink()
        for cached in CACHE.glob("icons-*.json"):
            cached.unlink()
        apply(current())
    elif cmd == "current":
        print(current())
    elif cmd == "apply":
        apply(current(), quiet="--quiet" in argv)
    elif cmd == "next":
        all_names = names()
        apply(all_names[(all_names.index(current()) + 1) % len(all_names)])
    elif cmd in ("set", "-s"):
        if len(argv) < 2:
            die("set: need a theme name")
        apply(argv[1])
    elif cmd in names():
        apply(cmd)
    elif cmd in ("-h", "--help", "help"):
        print(__doc__)
    else:
        die(f"unknown command: {cmd}\ntry: theme list")


if __name__ == "__main__":
    main(sys.argv[1:])
