-- Colorscheme, driven by ~/.config/theme.
--
-- lua/theme.lua is generated by `theme set <name>` and names both the active
-- colorscheme and the palette behind it. All three plugins are installed; only
-- the active one calls apply(), so nvim never loads two colorschemes.
-- Read at *config* time rather than here at spec-load time, and via dofile
-- rather than require. theme.lua is the one file here that changes between nvim
-- runs, and both Neovim's module cache and lazy's spec cache can serve a stale
-- copy of it — which brings nvim up on the previous theme, silently. See
-- lua/themeload.lua.
local themeload = require("themeload")

-- Highlights the shell keeps in sync across every theme. The comment colour is
-- the point of the exercise: the stock schemes sink comments too far into the
-- background, so it is pinned at a measured contrast ratio instead.
local function overrides(colors)
	local hl = vim.api.nvim_set_hl
	hl(0, "Comment", { fg = colors.comment, italic = true })
	hl(0, "@comment", { fg = colors.comment, italic = true })
	hl(0, "NormalFloat", { bg = "NONE" })
	hl(0, "FloatBorder", { bg = "NONE", fg = colors.accent })
	hl(0, "WinSeparator", { fg = colors.outline })
end

local function apply(name, colors)
	-- Say so rather than leaving nvim on whatever was loaded before. A
	-- colorscheme whose plugin is not installed reads as "the theme did not
	-- change", which gives no clue that a plugin is missing.
	local applied, err = pcall(vim.cmd.colorscheme, name)
	if not applied then
		vim.notify(
			("theme: colorscheme %q failed to load — is its plugin installed? (:Lazy sync)\n%s")
				:format(name, err),
			vim.log.levels.WARN
		)
		return
	end
	overrides(colors)
	-- Re-apply if a colorscheme is loaded later by hand.
	vim.api.nvim_create_autocmd("ColorScheme", { callback = function() overrides(colors) end })
end

-- applyIfActive is what each plugin's config calls: load the palette fresh, and
-- act only if this is the scheme it names.
local function applyIfActive(name)
	local theme, warning = themeload.get()
	if warning then
		vim.notify("theme: " .. warning, vim.log.levels.WARN)
	end
	if theme.colorscheme == name then
		apply(name, theme.colors)
	end
	return theme
end

return {
	{
		"navarasu/onedark.nvim",
		name = "onedark",
		lazy = false,
		priority = 1000,
		config = function()
			require("onedark").setup({
				style = "deep",
				transparent = true,
				lualine = { transparent = true },
			})
			applyIfActive("onedark")
		end,
	},

	{
		-- Ice Blue has no upstream scheme; nightfox takes a full palette
		-- override, so nordfox is used as the carrier and repainted from
		-- theme.lua. That keeps nvim on exactly the same hexes as the bar.
		"EdenEast/nightfox.nvim",
		lazy = false,
		priority = 1000,
		config = function()
			local colors = themeload.get().colors
			require("nightfox").setup({
				options = { transparent = true, styles = { comments = "italic" } },
				palettes = {
					nordfox = {
						black = { base = colors.base, bright = colors.surfaceBright, dim = colors.dim },
						red = { base = colors.red, bright = colors.red, dim = colors.red },
						green = { base = colors.green, bright = colors.green, dim = colors.green },
						yellow = { base = colors.yellow, bright = colors.yellow, dim = colors.orange },
						blue = { base = colors.blue, bright = colors.cyan, dim = colors.blue },
						magenta = { base = colors.purple, bright = colors.purple, dim = colors.purple },
						cyan = { base = colors.cyan, bright = colors.cyan, dim = colors.blue },
						white = { base = colors.fg, bright = colors.fg, dim = colors.fgDim },
						orange = { base = colors.orange, bright = colors.orange, dim = colors.orange },
						pink = { base = colors.purple, bright = colors.purple, dim = colors.purple },

						comment = colors.comment,
						bg0 = colors.dim,
						bg1 = colors.base,
						bg2 = colors.surface,
						bg3 = colors.surfaceBright,
						bg4 = colors.outline,
						fg0 = colors.fg,
						fg1 = colors.fg,
						fg2 = colors.fgDim,
						fg3 = colors.fgFaint,
						sel0 = colors.surfaceBright,
						sel1 = colors.outline,
					},
				},
			})
			applyIfActive("nordfox")
		end,
	},

	{
		"sainnhe/everforest",
		lazy = false,
		priority = 1000,
		config = function()
			vim.g.everforest_background = "medium"
			vim.g.everforest_transparent_background = 1
			vim.g.everforest_enable_italic = 1
			-- "high" lifts comments and greys out of the background, which is
			-- the whole reason for switching schemes.
			vim.g.everforest_ui_contrast = "high"
			applyIfActive("everforest")
		end,
	},
}
