;;; theme.el -*- lexical-binding: t; -*-
;; GENERATED by ~/.config/theme — edit themes/evergreen.json and run `theme apply`.
;;
;; config.el loads this. The face overrides mirror the ones that used to be
;; hardcoded there (true-black background, cyan child-frame borders) but track
;; the active palette instead.

(setq doom-theme 'doom-evergreen)

(custom-set-faces!
  '(default              :background "#232a2e")
  '(solaire-default-face :background "#232a2e")
  '(hl-line              :background "#343f44")
  '(child-frame-border   :background "#a7c080")
  '(vertical-border      :foreground "#a7c080")
  ;; The reason this file exists: comment contrast. Themes vary in how far
  ;; they sink comments into the background; this pins them at a measured
  ;; ratio against the editor background instead.
  '(font-lock-comment-face :foreground "#93a08f")
  '(font-lock-doc-face     :foreground "#93a08f")
  '(mode-line              :family "UbuntuMono Nerd Font")
  '(mode-line-inactive     :family "UbuntuMono Nerd Font"))
