-- GENERATED by ~/.config/theme — edit themes/evergreen.json and run `theme apply`.
--
-- lua/plugins/colorscheme.lua reads this to pick the colorscheme and to patch
-- the handful of highlights (comments, float borders) the shell keeps in sync.
return {
	name = "evergreen",
	colorscheme = "everforest",
	colors = {
		base = "#2d353b",
		dim = "#232a2e",
		surface = "#343f44",
		surfaceBright = "#3d484d",
		outline = "#4f585e",
		fg = "#d3c6aa",
		fgDim = "#9da9a0",
		fgFaint = "#7a8478",
		comment = "#93a08f",
		red = "#e67e80",
		green = "#a7c080",
		yellow = "#dbbc7f",
		blue = "#7fbbb3",
		purple = "#d699b6",
		cyan = "#83c092",
		orange = "#e69875",
		accent = "#a7c080",
	},
}
