-- Colorscheme, driven by ~/.config/theme.
--
-- lua/theme.lua is generated by `theme set <name>` and names both the active
-- colorscheme and the palette behind it. All three plugins are installed; only
-- the active one calls apply(), so nvim never loads two colorschemes.
local theme = require("theme")
local colors = theme.colors

-- Highlights the shell keeps in sync across every theme. The comment colour is
-- the point of the exercise: the stock schemes sink comments too far into the
-- background, so it is pinned at a measured contrast ratio instead.
local function overrides()
	local hl = vim.api.nvim_set_hl
	hl(0, "Comment", { fg = colors.comment, italic = true })
	hl(0, "@comment", { fg = colors.comment, italic = true })
	hl(0, "NormalFloat", { bg = "NONE" })
	hl(0, "FloatBorder", { bg = "NONE", fg = colors.accent })
	hl(0, "WinSeparator", { fg = colors.outline })
end

local function apply(name)
	vim.cmd.colorscheme(name)
	overrides()
	-- Re-apply if a colorscheme is loaded later by hand.
	vim.api.nvim_create_autocmd("ColorScheme", { callback = overrides })
end

local function active(name)
	return theme.colorscheme == name
end

return {
	{
		"navarasu/onedark.nvim",
		name = "onedark",
		lazy = false,
		priority = 1000,
		config = function()
			require("onedark").setup({
				style = "deep",
				transparent = true,
				lualine = { transparent = true },
			})
			if active("onedark") then
				apply("onedark")
			end
		end,
	},

	{
		-- Ice Blue has no upstream scheme; nightfox takes a full palette
		-- override, so nordfox is used as the carrier and repainted from
		-- theme.lua. That keeps nvim on exactly the same hexes as the bar.
		"EdenEast/nightfox.nvim",
		lazy = false,
		priority = 1000,
		config = function()
			require("nightfox").setup({
				options = { transparent = true, styles = { comments = "italic" } },
				palettes = {
					nordfox = {
						black = { base = colors.base, bright = colors.surfaceBright, dim = colors.dim },
						red = { base = colors.red, bright = colors.red, dim = colors.red },
						green = { base = colors.green, bright = colors.green, dim = colors.green },
						yellow = { base = colors.yellow, bright = colors.yellow, dim = colors.orange },
						blue = { base = colors.blue, bright = colors.cyan, dim = colors.blue },
						magenta = { base = colors.purple, bright = colors.purple, dim = colors.purple },
						cyan = { base = colors.cyan, bright = colors.cyan, dim = colors.blue },
						white = { base = colors.fg, bright = colors.fg, dim = colors.fgDim },
						orange = { base = colors.orange, bright = colors.orange, dim = colors.orange },
						pink = { base = colors.purple, bright = colors.purple, dim = colors.purple },

						comment = colors.comment,
						bg0 = colors.dim,
						bg1 = colors.base,
						bg2 = colors.surface,
						bg3 = colors.surfaceBright,
						bg4 = colors.outline,
						fg0 = colors.fg,
						fg1 = colors.fg,
						fg2 = colors.fgDim,
						fg3 = colors.fgFaint,
						sel0 = colors.surfaceBright,
						sel1 = colors.outline,
					},
				},
			})
			if active("nordfox") then
				apply("nordfox")
			end
		end,
	},

	{
		"sainnhe/everforest",
		lazy = false,
		priority = 1000,
		config = function()
			vim.g.everforest_background = "medium"
			vim.g.everforest_transparent_background = 1
			vim.g.everforest_enable_italic = 1
			-- "high" lifts comments and greys out of the background, which is
			-- the whole reason for switching schemes.
			vim.g.everforest_ui_contrast = "high"
			if active("everforest") then
				apply("everforest")
			end
		end,
	},
}
